- examples/view_with_email_alert.tf
- examples/view_with_email_pagerduty_and_webhook_alerts.tf
- examples/view_with_two_email_alerts.tf
- logdna/resource_view_test.go
Improve coveralls coverage by testing updates and error-handling.
Ref: LOG-7721
Semver: Patch
> Adds tests

- README.md
- docs/resources/logdna_view.md
- examples/view_with_email_pagerduty_and_webhook_alerts.tf
- examples/view_with_webhook_alert.tf
- go.mod
- logdna/client.go
- logdna/provider.go
- logdna/resource_view.go
- logdna/resource_view_test.go
- main.go
Updates resource_view code to support nesting body templates, updates docs to reflect these changes and adds an example config file.
Additionally fixes the badge on the README to reflect current coverage, updates the go.mod to point to Github and improves tests to better cover error-handling.
Ref: LOG-7689, LOG-7779
Semver: Patch
> Adds support for nesting bodytemplates and improves tests to better cover error-handling

- .circleci/config.yml
- .gitignore
- Makefile
- logdna/provider.go
- logdna/provider_test.go
- logdna/request.go
- logdna/request_types.go
- logdna/request_types_test.go
- logdna/resource_alert.go
- logdna/resource_alert_test.go
- logdna/resource_view.go
- logdna/resource_view_test.go
- logdna/response_types.go
- logdna/response_types_test.go
**fix: CI should use `make testcov` and use a coverage dir**
---
**refactor: Bring presetalert resources calls to new style**
---
**refactor: Abstractions to allow req/res parsing for multiple types**
> refactor: Bring presetalert resources calls to new style

- .gitignore
- README.md
- docs/index.md
- docs/resources/logdna_alert.md
- docs/resources/logdna_view.md
- examples/many_views.tf
Some of the technical docs needed to be cleaned up in terms of
how we show parameter types and default values. Various other
small corrections, too.
> docs: Groom the documentation

- docs/resources/logdna_alert.md
- docs/resources/logdna_view.md
- logdna/resource_alert.go
- logdna/resource_alert_test.go
- logdna/resource_view.go
- logdna/resource_view_test.go
This adds the necessary configuration to view and alert resources
to support `terraform import`. There is nothing extra needed here,
this allows all of the "native" import behavior to work as it should.
Ref: LOG-10221
> feat: enable `terraform import` for alerts/views

- Jenkinsfile
- Makefile
- docs/resources/logdna_stream_config.md
- docs/resources/logdna_stream_exclusion.md
- examples/stream_config.tf
- examples/stream_exclusions.tf
- logdna/provider.go
- logdna/request.go
- logdna/request_types.go
- logdna/resource_stream_config.go
- logdna/resource_stream_config_test.go
- logdna/resource_stream_exclusion.go
- logdna/resource_stream_exclusion_test.go
- logdna/response_types.go
**Note**: Tests are expected to fail currently as the API is not publicly available, but this is ready for review.
**feat(stream): add logdna_stream_config resource**
The `logdna_stream_config` resource manages the Event Streaming
setup for a given account.
Ref: LOG-10208
---
**feat(stream): add logdna_stream_exclusion resource**
The `logdna_stream_exclusion` resource manages Event Streaming
exclusions for an account.
Ref: LOG-10207
---
**fix(ci): include the GIT_BRANCH in the postcov step**
Jenkins runs this step in a detacted head state, so the `GIT_BRANCH`
needs to be exposed to the build container in order for the coveralls
coverage report to link to the proper branch.
Also includes HTML coverage report generation in the local test target.
> feat(stream): add stream_config and stream_exclusion resources

- Jenkinsfile
- Makefile
- README.md
This modifies the release step so that we get automatic
version bumps and releases when merging to `main`. Releases
will still be created as a "draft" in GitHub, so we can control
when they get pulled into the registry.
This does not include any provisions for handling pre-releases.
Instead, that can be accomplished by manually downloading the
appropriate binary from the draft release.
> ci: add automatic versioning and release builds

- Makefile
- logdna/resource_stream_exclusion.go
- logdna/resource_stream_exclusion_test.go
The exclusion rules created for Event Streaming configurations al-
ready have IDs which can be used as reference properties. To match
the behavor in our webapp, we opted to update the schemas on API +
TF to set the `title` property to optional. In the UI, the title
can be omitted which will still result in the creation of a valid
exclusion rule. This commit aligns the TF behavior with web.
Semver: patch
Ref: LOG-10750
> fix(stream_exclusion_rule): set `title` property to optional

- docs/data-sources/logdna_alert.md
- logdna/data_source_alert.go
- logdna/data_source_alert_test.go
- logdna/provider.go
Creates a `logdna_alert` data source which provides support for
remotely fetching information from existing preset alerts. Added
tests, updated the documentation, and included it in the provider.
Semver: minor
Ref: LOG-10590
> feat(alerts): add preset alert `logdna_alert` as a data source

- docs/data-sources/logdna_alert.md
- docs/resources/logdna_alert.md
- logdna/common_test.go
- logdna/data_source_alert.go
- logdna/data_source_alert_test.go
- logdna/provider_test.go
- logdna/request_types.go
- logdna/resource_alert.go
- logdna/resource_alert_test.go
- logdna/resource_view.go
- logdna/resource_view_test.go
- logdna/response_types.go
- logdna/response_types_test.go
Defines the `slack_channel` argument in the schemas for resources
`logdna_alert` + `logdna_view` and the data source `logdna_alert`.
This facilitates the ability to integrate preset alerts and view-
specific alerts with Slack. Updated the tests accordingly and did
quite a bit of housecleaning to modularize & dedupe some code.
Ref: LOG-10589
> [LOG-10589] feat: add slack integration to alerts & views

- Jenkinsfile
- instead of re-writing the git config, use the `$GIT_ASKPASS` script in
Jenkins' Managed Config Files for authentication
ref: REL-1096
> fix(ci): set `GIT_ASKPASS` for auth

- docs/resources/logdna_key.md
- logdna/common_test.go
- logdna/data_source_alert_test.go
- logdna/provider.go
- logdna/provider_test.go
- logdna/request.go
- logdna/request_test.go
- logdna/request_types.go
- logdna/resource_alert_test.go
- logdna/resource_archive_test.go
- logdna/resource_category_test.go
- logdna/resource_ingestion_exclusion_test.go
- logdna/resource_key.go
- logdna/resource_key_test.go
- logdna/resource_stream_config_test.go
- logdna/resource_stream_exclusion_test.go
- logdna/resource_view_test.go
- logdna/response_types.go
Introduces a new `logdna_key` resource to interact with the keys api to
manage service and ingestion keys.
This change includes some additional upkeep changes:
* Update `github.com/hashicorp/terraform-plugin-sdk/v2` to `v2.15.0`
* Remove duplicate code around existence testing
* Have requests use the http client attached to the provider instead of creating
a new one each time
* Ensure all tests respect the env `API_URL`
* Fix memory reference error when testing existence of non-existent resource
Ref: LOG-12483
Signed-off-by: Jacob Hull <jacob@planethull.com>
> feat: add new resource for keys api

- Jenkinsfile
A few recent PRs failed due to the fact
that there is no access to the fork repository.
In this commit the version check enabled
only for the original Logdna repo
Ref: LOG13520
> chore(ci): skip version check for fork PRs

- README.md
This adds a note to the documentation about the conventional commit
types supported by `svu`, and also serves as a way to trigger a new
build.
Ref: LOG-13520
> fix: add note about conventional commit types

- docs/resources/logdna_index_rate_alert.md
- examples/index_rate_alert.tf
- logdna/common_test.go
- logdna/data_source_alert_test.go
- logdna/provider.go
- logdna/request_types.go
- logdna/resource_alert_test.go
- logdna/resource_index_rate_alert.go
- logdna/resource_index_rate_alert_test.go
- logdna/resource_view_test.go
- logdna/response_types.go
Added Index Rate Alert resource
The API allows only PUT and GET endpoints
We use PUT endpoint for Create, Update and Delete resource functions
Delete resource disables index rate alert config
Ref: LOG-13487
> feat(index rate alert): add support of index rate alert api

- docs/resources/logdna_member.md
- logdna/provider.go
- logdna/request.go
- logdna/request_types.go
- logdna/resource_member.go
- logdna/resource_member_test.go
- logdna/response_types.go
Creates a new members resource to allow terraform to manage the members of their organizations. This new resource allows configuring the roles and groups as well!
Ref: LOG-12857
Signed-off-by: Jacob Hull <jacob@planethull.com>
Co-authored-by: Keerthika Damodaraswamy <keerthika.d@mezmo.com>
> feat(member): implement new members resources

- .gitignore
- Dockerfile
- Makefile
- README.md
- docs/resources/logdna_ingestion_exclusion.md
- examples/ingestion_exclusions.tf
- go.mod
- go.sum
- logdna/ingestion_exclusion_rule.go
- logdna/request.go
- logdna/request_test.go
- logdna/resource_ingestion_exclusion.go
- logdna/resource_ingestion_exclusion_test.go
This publishes #80 and #81 as a new release.
> Add support for indexonly exclusion rules and bump Go version

- Jenkinsfile
Don't use multiple agents. This should fix release builds so that they are not flaky.
> chore: update jenkins config

- docs/resources/logdna_ingestion_exclusion.md
The `indexonly` attribute is a poorly named attribute. This change updates the docs to match what it actually does.
> fix: correct indexonly docs

- logdna/request.go
- logdna/request_test.go
Only set the "Content-Type" of a request to "application/json" only if the request includes a body. This ensures the "Content-Type" is appropriate for the request and is interpretted correctly by the API.
Signed-off-by: Jacob Hull <jacob@planethull.com>
> fix: set request content-type based on payload

- docs/resources/logdna_alert.md
- docs/resources/logdna_view.md
Clarifies description for both the `immediate` and `terminal` fields to make it clear at least one of them are required to be true for presence alerts. Fixes #105.
Update the view resource documentation with the `slack_channel`. Fixes #85.
> docs(alerts): clarify immedaite/terminal and add slack_channel to views

- logdna/request.go
- logdna/request_test.go
Given a serviceKey with the format ^st[a-z]_ set the auth scheme to Token in the authorization header. This will allow people to continue to tuse this provider with new platform iam tokens
Ref: LOG-22014
> feat(request): Add support for new http authorization scheme
